branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: Hiri-dev
global:
  application_name: Hiri
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
